// src/lib/practice-data.ts

export interface Chapter {
    name: string;
    slug: string;
}

export interface Subject {
    name: string;
    slug: string;
    chapters: Chapter[];
}

export const practiceData: Subject[] = [
    {
        name: 'Physics',
        slug: 'physics',
        chapters: [
            { name: 'Units and Measurements', slug: 'units-and-measurements' },
            { name: 'Motion in a Straight Line', slug: 'motion-in-a-straight-line' },
            { name: 'Motion in a Plane', slug: 'motion-in-a-plane' },
            { name: "Newton's Laws of Motion", slug: 'newtons-laws-of-motion' },
            { name: 'Work, Energy and Power', slug: 'work-energy-and-power' },
            { name: 'System of Particles and Rotational Motion', slug: 'system-of-particles-and-rotational-motion' },
            { name: 'Gravitation', slug: 'gravitation' },
            { name: 'Mechanical Properties of Solids', slug: 'mechanical-properties-of-solids' },
            { name: 'Mechanical Properties of Fluids', slug: 'mechanical-properties-of-fluids' },
            { name: 'Thermal Properties of Matter', slug: 'thermal-properties-of-matter' },
            { name: 'Thermodynamics', slug: 'thermodynamics' },
            { name: 'Kinetic Theory', slug: 'kinetic-theory' },
            { name: 'Oscillations', slug: 'oscillations' },
            { name: 'Waves', slug: 'waves' },
            { name: 'Electric Charges and Fields', slug: 'electric-charges-and-fields' },
            { name: 'Electrostatic Potential and Capacitance', slug: 'electrostatic-potential-and-capacitance' },
            { name: 'Current Electricity', slug: 'current-electricity' },
            { name: 'Moving Charges and Magnetism', slug: 'moving-charges-and-magnetism' },
            { name: 'Magnetism and Matter', slug: 'magnetism-and-matter' },
            { name: 'Electromagnetic Induction', slug: 'electromagnetic-induction' },
            { name: 'Alternating Current', slug: 'alternating-current' },
            { name: 'Electromagnetic Waves', slug: 'electromagnetic-waves' },
            { name: 'Ray Optics and Optical Instruments', slug: 'ray-optics-and-optical-instruments' },
            { name: 'Wave Optics', slug: 'wave-optics' },
            { name: 'Dual Nature of Radiation and Matter', slug: 'dual-nature-of-radiation-and-matter' },
            { name: 'Atoms', slug: 'atoms' },
            { name: 'Nuclei', slug: 'nuclei' },
            { name: 'Semiconductor Electronics', slug: 'semiconductor-electronics' },
        ],
    },
    {
        name: 'Chemistry',
        slug: 'chemistry',
        chapters: [
            { name: 'Some Basic Concepts of Chemistry', slug: 'some-basic-concepts-of-chemistry' },
            { name: 'Structure of Atom', slug: 'structure-of-atom' },
            { name: 'Classification of Elements and Periodicity in Properties', slug: 'classification-of-elements' },
            { name: 'Chemical Bonding and Molecular Structure', slug: 'chemical-bonding' },
            { name: 'States of Matter', slug: 'states-of-matter' },
            { name: 'Thermodynamics', slug: 'thermodynamics-chem' },
            { name: 'Equilibrium', slug: 'equilibrium' },
            { name: 'Redox Reactions', slug: 'redox-reactions' },
            { name: 'Hydrogen', slug: 'hydrogen' },
            { name: 'The s-Block Elements', slug: 's-block-elements' },
            { name: 'The p-Block Elements (Group 13 & 14)', slug: 'p-block-elements-13-14' },
            { name: 'Organic Chemistry: Some Basic Principles and Techniques', slug: 'organic-chemistry-basic-principles' },
            { name: 'Hydrocarbons', slug: 'hydrocarbons' },
            { name: 'Environmental Chemistry', slug: 'environmental-chemistry' },
            { name: 'The Solid State', slug: 'solid-state' },
            { name: 'Solutions', slug: 'solutions' },
            { name: 'Electrochemistry', slug: 'electrochemistry' },
            { name: 'Chemical Kinetics', slug: 'chemical-kinetics' },
            { name: 'Surface Chemistry', slug: 'surface-chemistry' },
            { name: 'General Principles and Processes of Isolation of Elements', slug: 'isolation-of-elements' },
            { name: 'The p-Block Elements (Group 15 to 18)', slug: 'p-block-elements-15-18' },
            { name: 'The d- and f-Block Elements', slug: 'd-and-f-block-elements' },
            { name: 'Coordination Compounds', slug: 'coordination-compounds' },
            { name: 'Haloalkanes and Haloarenes', slug: 'haloalkanes-and-haloarenes' },
            { name: 'Alcohols, Phenols and Ethers', slug: 'alcohols-phenols-and-ethers' },
            { name: 'Aldehydes, Ketones and Carboxylic Acids', slug: 'aldehydes-ketones-carboxylic-acids' },
            { name: 'Amines', slug: 'amines' },
            { name: 'Biomolecules', slug: 'biomolecules' },
            { name: 'Polymers', slug: 'polymers' },
            { name: 'Chemistry in Everyday Life', slug: 'chemistry-in-everyday-life' },
        ],
    },
    {
        name: 'Biology',
        slug: 'biology',
        chapters: [
            { name: 'The Living World', slug: 'the-living-world' },
            { name: 'Biological Classification', slug: 'biological-classification' },
            { name: 'Plant Kingdom', slug: 'plant-kingdom' },
            { name: 'Animal Kingdom', slug: 'animal-kingdom' },
            { name: 'Morphology of Flowering Plants', slug: 'morphology-of-flowering-plants' },
            { name: 'Anatomy of Flowering Plants', slug: 'anatomy-of-flowering-plants' },
            { name: 'Structural Organisation in Animals', slug: 'structural-organisation-in-animals' },
            { name: 'Cell: The Unit of Life', slug: 'cell-the-unit-of-life' },
            { name: 'Biomolecules', slug: 'biomolecules-bio' },
            { name: 'Cell Cycle and Cell Division', slug: 'cell-cycle-and-cell-division' },
            { name: 'Transport in Plants', slug: 'transport-in-plants' },
            { name: 'Mineral Nutrition', slug: 'mineral-nutrition' },
            { name: 'Photosynthesis in Higher Plants', slug: 'photosynthesis' },
            { name: 'Respiration in Plants', slug: 'respiration-in-plants' },
            { name: 'Plant Growth and Development', slug: 'plant-growth-and-development' },
            { name: 'Digestion and Absorption', slug: 'digestion-and-absorption' },
            { name: 'Breathing and Exchange of Gases', slug: 'breathing-and-exchange-of-gases' },
            { name: 'Body Fluids and Circulation', slug: 'body-fluids-and-circulation' },
            { name: 'Excretory Products and their Elimination', slug: 'excretory-products' },
            { name: 'Locomotion and Movement', slug: 'locomotion-and-movement' },
            { name: 'Neural Control and Coordination', slug: 'neural-control-and-coordination' },
            { name: 'Chemical Coordination and Integration', slug: 'chemical-coordination-and-integration' },
            { name: 'Reproduction in Organisms', slug: 'reproduction-in-organisms' },
            { name: 'Sexual Reproduction in Flowering Plants', slug: 'sexual-reproduction-in-flowering-plants' },
            { name: 'Human Reproduction', slug: 'human-reproduction' },
            { name: 'Reproductive Health', slug: 'reproductive-health' },
            { name: 'Principles of Inheritance and Variation', slug: 'principles-of-inheritance' },
            { name: 'Molecular Basis of Inheritance', slug: 'molecular-basis-of-inheritance' },
            { name: 'Evolution', slug: 'evolution' },
            { name: 'Human Health and Disease', slug: 'human-health-and-disease' },
            { name: 'Strategies for Enhancement in Food Production', slug: 'food-production-enhancement' },
            { name: 'Microbes in Human Welfare', slug: 'microbes-in-human-welfare' },
            { name: 'Biotechnology: Principles and Processes', slug: 'biotechnology-principles' },
            { name: 'Biotechnology and Its Applications', slug: 'biotechnology-applications' },
            { name: 'Organisms and Populations', slug: 'organisms-and-populations' },
            { name: 'Ecosystem', slug: 'ecosystem' },
            { name: 'Biodiversity and Conservation', slug: 'biodiversity-and-conservation' },
            { name: 'Environmental Issues', slug: 'environmental-issues' },
        ],
    },
];
