// src/lib/questions/physics/newtons-laws-of-motion/neet-flashback.ts
import type { Question } from '@/lib/types';

const questions: Question[] = [
  {"questionNumber": 1, "questionText": "A person of mass 60 kg is inside a lift of mass 940 kg and presses the button on control panel. The lift starts moving upwards with an acceleration 1.0 m/s². If g = 10 ms⁻², the tension in the supporting cable is:", "questionImageURL": "", "options": {"A": "8600 N", "B": "9680 N", "C": "11000 N", "D": "1200 N"}, "correctAnswer": "C"},
  {"questionNumber": 2, "questionText": "A body of mass M hits normally a rigid wall with velocity V and bounces back with the same speed. The impulse experienced by the body is:", "questionImageURL": "", "options": {"A": "MV", "B": "1.5 MV", "C": "2 MV", "D": "Zero"}, "correctAnswer": "C"},
  {"questionNumber": 3, "questionText": "Three blocks with masses m, 2m and 3m are connected by strings as shown in the figure. After an upward force F is applied on block m, the masses move upward at constant speed v. What is the net force on the block of mass 2m? (g is the acceleration due to gravity)", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q3.png?alt=media", "options": {"A": "2mg", "B": "3mg", "C": "6mg", "D": "zero"}, "correctAnswer": "D"},
  {"questionNumber": 4, "questionText": "A system consists of three masses m₁, m₂, and m₃ connected by a string passing over a pulley P. The mass m₁ hangs freely and m₂ and m₃ are on a rough horizontal table (the coefficient of friction = µ). The pulley is frictionless and is of negligible mass. The downward acceleration of mass m₁ is: (Assume m₁ = m₂ = m₃ = m)", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q4.png?alt=media", "options": {"A": "g(1-2µ)/9", "B": "2gµ/3", "C": "g(1-2µ)/3", "D": "g(1-2µ)/2"}, "correctAnswer": "C"},
  {"questionNumber": 5, "questionText": "The force 'F' acting on a particle of mass 'm' is indicated by the force-time graph shown below. The change in momentum of the particle over the time interval from zero to 8 s is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q5.png?alt=media", "options": {"A": "24 Ns", "B": "20 Ns", "C": "12 Ns", "D": "6 Ns"}, "correctAnswer": "C"},
  {"questionNumber": 6, "questionText": "A balloon with mass 'm' is descending down with an acceleration 'a' (where a < g). How much mass should be removed from it so that it starts moving up with acceleration 'a'? (Assume that its volume does not change)", "questionImageURL": "", "options": {"A": "2ma/(g+a)", "B": "2ma/(g-a)", "C": "ma/(g+a)", "D": "ma/(g-a)"}, "correctAnswer": "A"},
  {"questionNumber": 7, "questionText": "A block A of mass m₁ rests on a horizontal table. A light string connected to it passes over a frictionless pulley at the edge of table and from its other end another block B of mass m₂ is suspended. The coefficient of kinetic friction between the block and the table is µₖ. When the block A is sliding on the table, the tension in the string is:", "questionImageURL": "", "options": {"A": "(m₂ - µₖm₁)g / (m₁ + m₂)", "B": "m₁m₂(1 + µₖ)g / (m₁ + m₂)", "C": "(m₂ + µₖm₁)g / (m₁ + m₂)", "D": "m₁m₂(1 - µₖ)g / (m₁ + m₂)"}, "correctAnswer": "B"},
  {"questionNumber": 8, "questionText": "Three blocks A, B and C of masses 4 kg, 2 kg and 1 kg respectively, are in contact on a frictionless surface, as shown. If a force of 14 N is applied on the 4 kg block, then the contact force between A and B is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q8.png?alt=media", "options": {"A": "6 N", "B": "8 N", "C": "18 N", "D": "2 Ns"}, "correctAnswer": "A"},
  {"questionNumber": 9, "questionText": "A plank with a box on it at one end is gradually raised about the other end. As the angle of inclination with the horizontal reaches 30°, the box starts to slip and slides 4.0 m down the plank in 4.0s. The coefficients of static and kinetic friction between the box and the plank will be, respectively:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q9.png?alt=media", "options": {"A": "0.4 and 0.3", "B": "0.6 and 0.6", "C": "0.6 and 0.5", "D": "0.5 and 0.6"}, "correctAnswer": "C"},
  {"questionNumber": 10, "questionText": "A rigid ball of mass m strikes a rigid wall at 60° and gets reflected without loss of speed as shown in the figure below. The value of impulse imparted by the wall on the ball will be:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q10.png?alt=media", "options": {"A": "mV/2", "B": "mV/3", "C": "mV", "D": "2mV"}, "correctAnswer": "C"},
  {"questionNumber": 11, "questionText": "Two blocks A and B of masses 3m and m respectively are connected by a massless and inextensible string. The whole system is suspended by a massless spring as shown in figure. The magnitudes of acceleration of A and B immediately after the string is cut, are respectively:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q11.png?alt=media", "options": {"A": "g/3, g", "B": "g, g", "C": "g/3, g/3", "D": "g, g/3"}, "correctAnswer": "A"},
  {"questionNumber": 12, "questionText": "Which of the following statement is incorrect?", "questionImageURL": "", "options": {"A": "Rolling friction is smaller than Sliding friction", "B": "Limiting value of Static friction is directly proportional to Normal reactions", "C": "Frictional force opposes the relative motion", "D": "Coefficient of Sliding friction has dimensions of length"}, "correctAnswer": "D"},
  {"questionNumber": 13, "questionText": "A block of mass m is placed on a smooth inclined wedge ABC of inclination θ as shown in the figure. The wedge is given an acceleration 'a' towards the right. The relation between 'a' and θ for the block to remain stationary on the wedge is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q13.png?alt=media", "options": {"A": "a = g/cosecθ", "B": "a = g/sinθ", "C": "a = g cosθ", "D": "a = g tanθ"}, "correctAnswer": "D"},
  {"questionNumber": 14, "questionText": "A truck is stationary and has a bob suspended by a light string, in a frame attached to the truck. The truck, suddenly moves to the right with an acceleration of a. The pendulum will tilt:", "questionImageURL": "", "options": {"A": "to the left and angle of inclination of the pendulum with the vertical is sin⁻¹(g/a)", "B": "to the left and angle of inclination of the pendulum with the vertical is tan⁻¹(a/g)", "C": "to the left and angle of inclination of the pendulum with the vertical is sin⁻¹(a/g)", "D": "to the left and angle of inclination of the pendulum with the vertical is tan⁻¹(g/a)"}, "correctAnswer": "B"},
  {"questionNumber": 15, "questionText": "A body of mass m is kept on a rough horizontal surface (coefficient of friction = µ). A horizontal force is applied on the body, but it does not move. The resultant of normal reaction and the frictional force acting on the object is given by F, where F is:", "questionImageURL": "", "options": {"A": "|F| = mg + µmg", "B": "|F| = µmg", "C": "|F| ≤ mg√(1+µ²)", "D": "|F| = mg"}, "correctAnswer": "C"},
  {"questionNumber": 16, "questionText": "Calculate the acceleration of the block and trolly system shown in the figure. The coefficient of kinetic friction between the trolly and the surface is 0.05. (g = 10 m/s², mass of the string is negligible and no other friction exists).", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q16.png?alt=media", "options": {"A": "1.25 m/s²", "B": "1.50 m/s²", "C": "1.66 m/s²", "D": "1.00 m/s²"}, "correctAnswer": "A"},
  {"questionNumber": 17, "questionText": "Two bodies of mass 4kg and 6kg are tied to the ends of a massless string. The string passes over a pulley which is frictionless (see figure). The acceleration of the system in terms of acceleration due to gravity (g) is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q17.png?alt=media", "options": {"A": "g/10", "B": "g", "C": "g/2", "D": "g/5"}, "correctAnswer": "D"},
  {"questionNumber": 18, "questionText": "A football player is moving southward and suddenly turns eastward with the same speed to avoid an opponent. The force that acts on the player while turning is", "questionImageURL": "", "options": {"A": "Along northward", "B": "Along north-east", "C": "Along south-west", "D": "Along eastward"}, "correctAnswer": "B"},
  {"questionNumber": 19, "questionText": "Calculate the maximum acceleration of a moving car so that a body lying on the floor of the car remains stationary. The coefficient of static friction between the body and the floor is 0.15 (g = 10 m s⁻²).", "questionImageURL": "", "options": {"A": "150 m s⁻²", "B": "1.5 m s⁻²", "C": "50 m s⁻²", "D": "1.2 m s⁻²"}, "correctAnswer": "B"},
  {"questionNumber": 20, "questionText": "A horizontal force 10 N is applied to a block A as shown in figure. The mass of blocks A and B are 2 kg and 3 kg respectively. The blocks slide over a frictionless surface. The force exerted by block A on block B is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q20.png?alt=media", "options": {"A": "Zero", "B": "4 N", "C": "6 N", "D": "10 N"}, "correctAnswer": "C"},
  {"questionNumber": 21, "questionText": "There are two inclined surface of equal length (L) and same angle of inclination 45° with the horizontal. One of them is rough and the other is perfectly smooth. A given body takes 2 times as much time to slide down on rough surface than on the smooth surface. The coefficient of kinetic friction (µₖ) between the object and the rough surface is close to:", "questionImageURL": "", "options": {"A": "0.25", "B": "0.40", "C": "0.5", "D": "0.75"}, "correctAnswer": "D"},
  {"questionNumber": 22, "questionText": "A ball of mass 0.5 kg is dropped from a height of 40 m. The ball hits the ground and rises to a height of 10 m. The impulse imparted to the ball during its collision with the ground is (Take g = 9.8 m/s²)", "questionImageURL": "", "options": {"A": "21 Ns", "B": "7 Ns", "C": "0", "D": "84 Ns"}, "correctAnswer": "A"},
  {"questionNumber": 23, "questionText": "A uniform rod of mass 20 kg and length 5 m leans against a smooth vertical wall making an angle of 60° with it. The other end rests on a rough horizontal floor. The friction force that the floor exerts on the rod is (take g = 10 m/s²)", "questionImageURL": "", "options": {"A": "100 N", "B": "100√3 N", "C": "200 N", "D": "200√3 N"}, "correctAnswer": "B"}
]

export default questions;
