// src/lib/questions/physics/newtons-laws-of-motion/neet-rankers.ts
import type { Question } from '@/lib/types';

const questions: Question[] = [
  {"questionNumber": 1, "questionText": "A particle of mass m is at rest at the origin at time t = 0. It is subjected to a force F(t) = F₀e⁻ᵇᵗ in the x direction. Its speed v(t) is depicted by which of the following curves?", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/rankers-nlm-q1.png?alt=media", "options": {"A": "Curve 1", "B": "Curve 2", "C": "Curve 3", "D": "Curve 4"}, "correctAnswer": "B"},
  {"questionNumber": 2, "questionText": "Two blocks A and B of masses 2m and m, respectively are connected by a massless and inextensible string. The whole system is suspended by a massless spring as shown in the figure. The magnitude of acceleration of A and B immediately after the string is cut, are respectively", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/q11_image.png?alt=media", "options": {"A": "g, g/2", "B": "g/2, g", "C": "g, g", "D": "g/2, g/2"}, "correctAnswer": "B"},
  {"questionNumber": 3, "questionText": "A coin is dropped in a lift. It takes time t₁ to reach the floor when lift is stationary. It takes time t₂ when lift is moving up with constant acceleration. Then", "questionImageURL": "", "options": {"A": "t₁ < t₂", "B": "t₁ > t₂", "C": "t₁ = t₂", "D": "t₁ >> t₂"}, "correctAnswer": "A"},
  {"questionNumber": 4, "questionText": "A man of mass m has fallen into a ditch of width d. Two of his friends are slowly pulling him out of the ditch by means of a light rope and the two halves of the rope makes an angle θ with the vertical. Show that the force exerted by each friend on the rope is", "questionImageURL": "", "options": {"A": "mg/(2tanθ)", "B": "mg/(2cosθ)", "C": "mg/(2sinθ)", "D": "mg/cosθ"}, "correctAnswer": "B"},
  {"questionNumber": 5, "questionText": "A rocket of mass 100 kg burns 0.1 kg of fuel per second. If velocity of exhaust gas is 1 km/s, then it lifts with an acceleration of", "questionImageURL": "", "options": {"A": "100 m/s²", "B": "1000 m/s²", "C": "10 m/s²", "D": "1 m/s²"}, "correctAnswer": "D"},
  {"questionNumber": 6, "questionText": "A body of mass 8 kg is suspended through two light springs X and Y connected in series as shown in the figure. The readings in X and Y respectively are:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/rankers-nlm-q6.png?alt=media", "options": {"A": "8kg, 8kg", "B": "4kg, 4kg", "C": "2kg, 6kg", "D": "6kg, 2kg"}, "correctAnswer": "A"},
  {"questionNumber": 7, "questionText": "Two masses m and M are attached to the strings as shown in the figure. If the system is in equilibrium, then", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/rankers-nlm-q7.png?alt=media", "options": {"A": "tanθ = 1+2m/M", "B": "tanθ = 1+2M/m", "C": "cotθ = 1+2m/M", "D": "cotθ = 1+2M/m"}, "correctAnswer": "B"},
  {"questionNumber": 8, "questionText": "A man of weight mg is standing in an elevator which is moving with an upward acceleration a. The apparent weight of the man is:", "questionImageURL": "", "options": {"A": "mg", "B": "m(g+a)", "C": "m(g-a)", "D": "m(a-g)"}, "correctAnswer": "B"},
  {"questionNumber": 9, "questionText": "Three equal weights of mass 2 kg each are hanging on a string passing over a fixed pulley as shown in figure. The tension in the string connecting weights B and C is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/rankers-nlm-q9.png?alt=media", "options": {"A": "zero", "B": "13.3 N", "C": "3.3 N", "D": "19.6 N"}, "correctAnswer": "B"},
  {"questionNumber": 10, "questionText": "A particle moves in the x-y plane under the action of a force F such that the value of its linear momentum (P) at any time t is, Px = 2 cos t, Py = 2 sin t. The angle θ between F and P at a given time t will be", "questionImageURL": "", "options": {"A": "90°", "B": "0°", "C": "180°", "D": "30°"}, "correctAnswer": "A"},
  {"questionNumber": 11, "questionText": "The time period of a simple pendulum measured inside a stationary lift is found to be T. If the lift starts accelerating upwards with an acceleration g/3, the time period is:", "questionImageURL": "", "options": {"A": "T√3", "B": "T√3/2", "C": "T/√3", "D": "T/3"}, "correctAnswer": "B"},
  {"questionNumber": 12, "questionText": "A block is kept on a frictionless inclined surface with angle of inclination 'α'. The incline is given an acceleration 'a' to keep the block stationary. Then 'a' is equal to", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/rankers-nlm-q12.png?alt=media", "options": {"A": "g", "B": "g tanα", "C": "g/tanα", "D": "g cosecα"}, "correctAnswer": "B"},
  {"questionNumber": 13, "questionText": "A satellite in force-free space sweeps stationary interplanetary dust at a rate dM/dt = αv, where M is the mass and v is the velocity of the satellite and α is a constant. What is the deceleration of the satellite?", "questionImageURL": "", "options": {"A": "-2αv²/M", "B": "-αv²/M", "C": "-αv²", "D": "-αv²/2M"}, "correctAnswer": "B"},
  {"questionNumber": 14, "questionText": "A block of mass m is placed on a smooth wedge of inclination θ. The whole system is accelerated horizontally so that the block does not slip on the wedge. The force exerted by the wedge on the block (g is acceleration due to gravity) will be:", "questionImageURL": "", "options": {"A": "mg/cosθ", "B": "mg cosθ", "C": "mg", "D": "mg sinθ"}, "correctAnswer": "A"},
  {"questionNumber": 15, "questionText": "A player caught a cricket ball of mass 150 g moving at a rate of 20 m/s. If the catching process is completed in 0.1 s, the force of the blow exerted by the ball on the hand of the player is equal to", "questionImageURL": "", "options": {"A": "150 N", "B": "3 N", "C": "30 N", "D": "300 N"}, "correctAnswer": "C"}
]
