// src/lib/questions/chemistry/isomerism/neet-flashback.ts
import type { Question } from '@/lib/types';

const questions: Question[] = [
  {"questionNumber": 1, "questionText": "Which of the following is not chiral :-", "questionImageURL": "", "options": {"A": "2-Butanol", "B": "2,3-Dibromo pentane", "C": "3-Bromo pentane", "D": "2-Hydroxy propanoic acid"}, "correctAnswer": "C"},
  {"questionNumber": 2, "questionText": "CH₃-CHCl-CH₂-CH₃ has a chiral centre which one of the following represents its R configuration", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q2.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "B"},
  {"questionNumber": 3, "questionText": "How many stereoisomer does this molecule have CH₃CH=CHCH₂CHBrCH₃", "questionImageURL": "", "options": {"A": "8", "B": "2", "C": "4", "D": "6"}, "correctAnswer": "C"},
  {"questionNumber": 4, "questionText": "Which of the following compounds will exhibit cis-trans (geometrical) isomerism?", "questionImageURL": "", "options": {"A": "1-Butanol", "B": "2-Butene", "C": "2-Butanol", "D": "2-Butyne"}, "correctAnswer": "B"},
  {"questionNumber": 5, "questionText": "In the following the most stable conformation of n-butane is :-", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q5.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "C"},
  {"questionNumber": 6, "questionText": "Which of the following conformers for ethylene glycol is most stable :-", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q6.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "C"},
  {"questionNumber": 7, "questionText": "Which of the following acids does not exhibit optical isomerism?", "questionImageURL": "", "options": {"A": "Lactic acid", "B": "Tartaric acid", "C": "Maleic acid", "D": "a-amino acids"}, "correctAnswer": "C"},
  {"questionNumber": 8, "questionText": "Which of the following is optically active:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q8.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "B"},
  {"questionNumber": 9, "questionText": "The IUPAC name of the following compound is:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q9.png?alt=media", "options": {"A": "cis-2-chloro-3-iodo-2-pentene", "B": "trans-2-chloro-3-iodo-2-pentene", "C": "cis-3-iodo-4-chloro-3-pentene", "D": "trans-3-iodo-4-chloro-3-pentene"}, "correctAnswer": "B"},
  {"questionNumber": 10, "questionText": "Two possible stereo-structures of CH₃CHOH.COOH, which are optically active, are called :-", "questionImageURL": "", "options": {"A": "Enantiomers", "B": "Mesomers", "C": "Diastereomers", "D": "Atropisomers"}, "correctAnswer": "A"},
  {"questionNumber": 11, "questionText": "The number of structural isomers possible from the molecular formula C₃H₉N is:", "questionImageURL": "", "options": {"A": "2", "B": "4", "C": "3", "D": "5"}, "correctAnswer": "C"},
  {"questionNumber": 12, "questionText": "Which of the following pair is diastereomers", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q12.png?alt=media", "options": {"A": "i, ii", "B": "i, iii", "C": "i, iv", "D": "iii, iv"}, "correctAnswer": "D"},
  {"questionNumber": 13, "questionText": "Which of the following biphenyls is optically active?", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q13.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "B"},
  {"questionNumber": 14, "questionText": "The correct statement regarding the comparison of staggered and eclipsed conformation of ethane, is :-", "questionImageURL": "", "options": {"A": "The staggered conformation of ethane is less stable than eclipsed conformation, because staggered conformation has torsional strain", "B": "The eclipsed conformation of ethane is more stable than staggered conformation, because eclipsed conformation has no torsional strain", "C": "The eclipsed conformation of ethane is more stable than staggered conformation even through the eclipsed conformation has torsional strain", "D": "The staggered conformation of ethane is more stable than eclipsed conformation, because staggered conformation has no torsional strain."}, "correctAnswer": "D"},
  {"questionNumber": 15, "questionText": "The correct corresponding order names of four aldoses with configuration given below respectively, is :-", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_flashback_q15.png?alt=media", "options": {"A": "L-erythrose, L-threose, D-erythrose, D-threose", "B": "D-erythrose, D-threose, L-erythrose, L-threose", "C": "L-erythrose, L-threose, L-erythrose, D-threose", "D": "D-threose, D-erythrose, L-threose, L-erythrose"}, "correctAnswer": "B"},
  {"questionNumber": 16, "questionText": "With respect to the conformers of ethane, which of the following statements is true?", "questionImageURL": "", "options": {"A": "Bond angle changes but bond length remains same", "B": "Both bond angle and bond length change", "C": "Both bond angles and bond length remains same", "D": "Bond angle remains same but bond length changes"}, "correctAnswer": "C"},
  {"questionNumber": 17, "questionText": "The compound which shows metamerism is :", "questionImageURL": "", "options": {"A": "C₅H₁₂", "B": "C₃H₈O", "C": "C₃H₆O", "D": "C₄H₁₀O"}, "correctAnswer": "D"},
  {"questionNumber": 18, "questionText": "Dihedral angle of least stable conformer of ethane is:", "questionImageURL": "", "options": {"A": "120°", "B": "180°", "C": "60°", "D": "0°"}, "correctAnswer": "D"},
  {"questionNumber": 19, "questionText": "Which amongst the following compounds will show geometrical isomerism?", "questionImageURL": "", "options": {"A": "Pent-1-ene", "B": "2,3-Dimethylbut-2-ene", "C": "2-Methylprop-1-ene", "D": "3,4-Dimethylhex-3-ene"}, "correctAnswer": "D"},
  {"questionNumber": 20, "questionText": "Statement I: The boiling point of three isomeric pentanes follows the order n-pentane > isopentane > neopentane. Statement II: When branching increases, the molecule attains a shape of sphere. This results in smaller surface area for contact, due to which the intermolecular forces between the spherical molecules are weak, thereby lowering the boiling point.", "questionImageURL": "", "options": {"A": "Both Statement I and Statement II are correct", "B": "Both Statement I and Statement II are incorrect", "C": "Statement I is correct but Statement II is incorrect", "D": "Statement I is incorrect but Statement II is correct"}, "correctAnswer": "A"},
  {"questionNumber": 21, "questionText": "Which one of the following compounds can exist as cis-trans isomers?", "questionImageURL": "", "options": {"A": "Pent-1-ene", "B": "2-Methylhex-2-ene", "C": "1,1-Dimethylcyclopropane", "D": "1,2-Dimethylcyclohexane"}, "correctAnswer": "D"},
  {"questionNumber": 22, "questionText": "Total number of possible isomers (both structural as well as stereoisomers) of cyclic ethers of molecular formula C₄H₈O is:", "questionImageURL": "", "options": {"A": "6", "B": "8", "C": "10", "D": "11"}, "correctAnswer": "C"}
];
export default questions;
