// src/lib/questions/chemistry/isomerism/topic-wise.ts
import type { Question } from '@/lib/types';

const questions: Question[] = [
  {"questionNumber": 1, "questionText": "Which of the following does not contain any asymmetric carbon but can show enantiomerism:-", "questionImageURL": "", "options": {"A": "Lactic acid", "B": "1,3-pentadiene", "C": "Tartaric acid", "D": "2,3-pentadiene"}, "correctAnswer": "D"},
  {"questionNumber": 2, "questionText": "Which of the following represents the structure having cis arrangement around each double bond:-", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q2.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "B"},
  {"questionNumber": 3, "questionText": "The complete IUPAC name of the compound :-", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q3.png?alt=media", "options": {"A": "(R)-1-Bromo-1-phenyl ethane", "B": "(S)-1-Bromo-1-phenyl ethane", "C": "(E)-1-Bromo-1-phenyl ethane", "D": "(Z)-1-Bromo-1-phenyl ethane"}, "correctAnswer": "A"},
  {"questionNumber": 4, "questionText": "Which one of the following is the most stable conformation of 2,3-butanediol :-", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q4.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "C"},
  {"questionNumber": 5, "questionText": "How many isomers of C₅H₁₁OH will be primary alcohols (exclude stereoisomers) :.", "questionImageURL": "", "options": {"A": "2", "B": "3", "C": "4", "D": "6"}, "correctAnswer": "C"},
  {"questionNumber": 6, "questionText": "The minimum number of carbon atoms in ketone to show metamerism:.", "questionImageURL": "", "options": {"A": "3", "B": "4", "C": "5", "D": "6"}, "correctAnswer": "C"},
  {"questionNumber": 7, "questionText": "The total number of configurational isomers of the given compound are :- CH₃-CH=CH-CHOH-CHOH-CH₃", "questionImageURL": "", "options": {"A": "2", "B": "4", "C": "6", "D": "8"}, "correctAnswer": "D"},
  {"questionNumber": 8, "questionText": "The given structures are:", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q8.png?alt=media", "options": {"A": "Enantiomers", "B": "Position isomers", "C": "Geometrical isomers", "D": "Homomers"}, "correctAnswer": "D"},
  {"questionNumber": 9, "questionText": "Which of the following is not a metamer of C₄H₁₀O", "questionImageURL": "", "options": {"A": "Diethyl ether", "B": "Methyl n-propyl ether", "C": "2-Methoxy propane", "D": "Isobutyl alcohol"}, "correctAnswer": "D"},
  {"questionNumber": 10, "questionText": "How many compounds among the following are chiral?", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q10.png?alt=media", "options": {"A": "1", "B": "2", "C": "3", "D": "4"}, "correctAnswer": "C"},
  {"questionNumber": 11, "questionText": "In which of the following compound syn anti configuration will given?", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q11.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "C"},
  {"questionNumber": 12, "questionText": "Calculate the total no. of geometrical isomers for the given structure?", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q12.png?alt=media", "options": {"A": "32", "B": "16", "C": "5", "D": "8"}, "correctAnswer": "D"},
  {"questionNumber": 13, "questionText": "Which of the following compound will be meso compound?", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q13.png?alt=media", "options": {"A": "Structure 1", "B": "Structure 2", "C": "Structure 3", "D": "Structure 4"}, "correctAnswer": "A"},
  {"questionNumber": 14, "questionText": "Match the column I and Column II", "questionImageURL": "", "options": {"A": "i-(s), ii-(q), iii-(r), iv-(p)", "B": "i-(s), ii-(q), iii-(p), iv-(r)", "C": "i-(q), ii-(s), iii-(r), iv-(p)", "D": "i-(q), ii-(s), iii-(p), iv-(r)"}, "correctAnswer": "D"},
  {"questionNumber": 15, "questionText": "Match each entry of Column I with those given in Column II.", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/isomerism_ranker_q15.png?alt=media", "options": {"A": "i-(p) ii-(s) iii-(r) iv-(q)", "B": "i-(q) ii-(r) iii-(p) iv-(s)", "C": "i-(q) ii-(r) iii-(s) iv-(p)", "D": "i-(r) ii-(q) iii-(s) iv-(p)"}, "correctAnswer": "C"}
];

export default questions;
