// src/lib/questions/biology/locomotion-and-movement/neet-flashback.ts
import type { Question } from '@/lib/types';

const questions: Question[] = [
  {"questionNumber": 1, "questionText": "Select the correct statement with respect to locomotion in humans:", "questionImageURL": "", "options": {"A": "The joint between adjacent vertebrae is a fibrous joint", "B": "A decreased level of progesterone causes osteoporosis in old people.", "C": "Accumulation of uric acid crystals in joints causes their inflammation", "D": "The vertebral column has 10 thoracic vertebrae"}, "correctAnswer": "C"},
  {"questionNumber": 2, "questionText": "The H-zone in the skeletal muscle Fibre is due to:", "questionImageURL": "", "options": {"A": "Extension of myosin filaments in the central portion of the A-band.", "B": "The absence of myofibrils in the central portion of A-band.", "C": "The central gap between myosin filaments in the A-band.", "D": "The central gap between actin filaments extending through myosin filaments in the A-band."}, "correctAnswer": "D"},
  {"questionNumber": 3, "questionText": "Stimulation of a muscle Fibre by a motor neuron occurs at:", "questionImageURL": "", "options": {"A": "The neuromuscular junction", "B": "The transverse tubules", "C": "The myofibril", "D": "The sarcoplasmic reticulum"}, "correctAnswer": "A"},
  {"questionNumber": 4, "questionText": "Select the correct matching of the type of the joint with the example in human skeletal system:", "questionImageURL": "", "options": {"A": "Cartilaginous joint - between frontal and parietal", "B": "Pivot joint - between third and fourth cervical vertebrae", "C": "Hinge joint - between humerus and pectoral girdle", "D": "Gliding joint - between carpals"}, "correctAnswer": "D"},
  {"questionNumber": 5, "questionText": "Glenoid cavity articulates:", "questionImageURL": "", "options": {"A": "Scapula with acromion", "B": "Clavicle with scapula", "C": "Humerus with scapula", "D": "Clavicle with acromion"}, "correctAnswer": "C"},
  {"questionNumber": 6, "questionText": "Which of the following is not a function of the skeletal system?", "questionImageURL": "", "options": {"A": "Locomotion", "B": "Production of erythrocytes", "C": "Storage of minerals", "D": "Production of body heat"}, "correctAnswer": "D"},
  {"questionNumber": 7, "questionText": "Which of the following joints would allow no movement?", "questionImageURL": "", "options": {"A": "Ball and Socket joint", "B": "Fibrous joint", "C": "Cartilaginous joint", "D": "Synovial joint"}, "correctAnswer": "B"},
  {"questionNumber": 8, "questionText": "Sliding filament theory can be best explained as:", "questionImageURL": "", "options": {"A": "Actin and Myosin filaments shorten and slide pass each other", "B": "Actin and Myosin filaments do not shorten but rather slide pass each other", "C": "When myofilaments slide pass each other, Myosin filaments shorten while Actin filaments do not shorten", "D": "When myofilaments slide pass each other Actin filaments shorten while Myosin filament do not shorten."}, "correctAnswer": "B"},
  {"questionNumber": 9, "questionText": "Name the ion responsible for unmasking of active sites for myosin for cross-bridge activity during muscle contraction:", "questionImageURL": "", "options": {"A": "Calcium", "B": "Magnesium", "C": "Sodium", "D": "Potassium"}, "correctAnswer": "A"},
  {"questionNumber": 10, "questionText": "Lack of relaxation between successive stimuli in sustained muscle contraction is known as:", "questionImageURL": "", "options": {"A": "Tetanus", "B": "Tonus", "C": "Spasm", "D": "Fatigue"}, "correctAnswer": "A"},
  {"questionNumber": 11, "questionText": "Osteoporosis, an age-related disease of skeletal system, may occur due to", "questionImageURL": "", "options": {"A": "Immune disorder affecting neuromuscular junction leading to fatigue", "B": "high concentration of Ca⁺⁺ and Na⁺", "C": "decreased level of estrogen", "D": "accumulation of uric acid leading to inflammation of joints."}, "correctAnswer": "C"},
  {"questionNumber": 12, "questionText": "Out of 'X' pairs of ribs in humans only 'Y' pairs are true ribs. Select the option that correctly represents values of X and Y provides their explanation:", "questionImageURL": "", "options": {"A": "X=12, Y=7; True ribs are attached dorsally to vertebral column and ventrally to the sternum.", "B": "X=12, Y=5; True ribs are attached dorsally to vertebral column and sternum on the two ends.", "C": "X=24, Y=7; True ribs are dorsally attached to vertebral column but are free on ventral side.", "D": "X=24, Y=12; True ribs are dorsally attached to vertebral column but are free on ventral side."}, "correctAnswer": "A"},
  {"questionNumber": 13, "questionText": "The pivot joint between atlas and axis is a type of:", "questionImageURL": "", "options": {"A": "Fibrous joint", "B": "Cartilaginous joint", "C": "Synovial joint", "D": "Saddle joint"}, "correctAnswer": "C"},
  {"questionNumber": 14, "questionText": "Calcium is important in skeletal muscle contraction because it:", "questionImageURL": "", "options": {"A": "Prevents the formation of bonds between the myosin cross bridges and the actin filament.", "B": "Binds to troponin to remove the masking of active sites on actin for myosin.", "C": "Detaches the myosin head from the actin filament.", "D": "Activates the myosin ATPase by binding to it."}, "correctAnswer": "B"},
  {"questionNumber": 15, "questionText": "Which of the following muscular disorders is inherited?", "questionImageURL": "", "options": {"A": "Myasthenia gravis", "B": "Botulism", "C": "Tetany", "D": "Muscular dystrophy"}, "correctAnswer": "D"},
  {"questionNumber": 16, "questionText": "Select the correct option.", "questionImageURL": "", "options": {"A": "Each rib is a flat thin bone and all the ribs are connected dorsally to the thoracic vertebrae and ventrally to the sternum.", "B": "There are seven pairs of vertebrosternal, three pairs of vertebrochondral and two pairs of vertebral ribs.", "C": "8th, 9th and 10th pairs of ribs articulate directly with the sternum", "D": "11th and 12th Pairs of ribs are connected to the sternum with the help of hyaline cartilage."}, "correctAnswer": "B"},
  {"questionNumber": 17, "questionText": "Match the following columns and select the correct option. Column - I: (a) Floating ribs, (b) Acromion, (c) Scapula, (d) Glenoid cavity; Column - II: (i) Located between second and seventh ribs, (ii) Head of the humerus, (iii) Clavicle, (iv) Do not connect with the sternum", "questionImageURL": "", "options": {"A": "a-(i), b-(iii), c-(ii), d-(iv)", "B": "a-(iii), b-(ii), c-(iv), d-(i)", "C": "a-(iv), b-(iii), c-(i), d-(ii)", "D": "a-(ii), b-(iv), c-(i), d-(iii)"}, "correctAnswer": "C"},
  {"questionNumber": 18, "questionText": "Match the following columns and select the correct option: Column-I: (a) Gout, (b) Osteoporosis, (c) Tetany, (d) Muscular dystrophy; Column-II: (i) Decreased levels of estrogen, (ii) Low Ca⁺⁺ ions in the blood, (iii) Accumulation of uric acid crystals, (iv) Auto immune disorder, (v) Genetic disorder", "questionImageURL": "", "options": {"A": "a-(iii), b-(i), c-(ii), d-(v)", "B": "a-(iv), b-(v), c-(i), d-(ii)", "C": "a-(i), b-(ii), c-(iii), d-(iv)", "D": "a-(ii), b-(i), c-(iii), d-(iv)"}, "correctAnswer": "A"},
  {"questionNumber": 19, "questionText": "Match List-I with List-II. List-I: (a) Scapula, (b) Cranium, (c) Sternum, (d) Vertebral column; List-II: (i) Cartilaginous joints, (ii) Flat bone, (iii) Fibrous joints, (iv) Triangular flat bone", "questionImageURL": "", "options": {"A": "a-(i), b-(iii), c-(ii), d-(iv)", "B": "a-(ii), b-(iii), c-(iv), d-(i)", "C": "a-(iv), b-(ii), c-(iii), d-(i)", "D": "a-(iv), b-(iii), c-(ii), d-(i)"}, "correctAnswer": "D"},
  {"questionNumber": 20, "questionText": "Chronic auto immune disorder affecting neuro muscular junction leading to fatigue, weakening and paralysis of skeletal muscle is called as:", "questionImageURL": "", "options": {"A": "Arthritis", "B": "Muscular dystrophy", "C": "Myasthenia gravis", "D": "Gout"}, "correctAnswer": "C"},
  {"questionNumber": 21, "questionText": "Given below are two statements: Statement I: Autoimmune disorder is a condition where body defense mechanism recognizes its own cells as foreign bodies. Statement II: Rheumatoid arthritis is a condition where body does not attack self-cells.", "questionImageURL": "", "options": {"A": "Both Statement I and Statement II are correct", "B": "Both Statement I and Statement II are incorrect", "C": "Statement I is correct but Statement II is incorrect", "D": "Statement I is incorrect but Statement II is correct"}, "correctAnswer": "C"},
  {"questionNumber": 22, "questionText": "Given below are two statements one is labelled as Assertion (A) and the other is labelled as Reason (R). Assertion (A): Osteoporosis is characterised by decreased bone mass and increased chance of fractures. Reason (R): Common cause of osteoporosis is increased levels of estrogen.", "questionImageURL": "", "options": {"A": "Both (A) and (R) are correct and (R) is the correct explanation of (A)", "B": "Both (A) and (R) are correct but (R) is not the correct explanation of (A)", "C": "(A) is correct but (R) is not correct", "D": "(A) is not correct but (R) is correct"}, "correctAnswer": "C"},
  {"questionNumber": 23, "questionText": "Which of the following is a correct match for disease and its symptoms?", "questionImageURL": "", "options": {"A": "Arthritis - Inflammed joints", "B": "Tetany High Ca²⁺ level causing rapid spasms.", "C": "Myasthenia gravis Genetic disorder resulting in weakening and paralysis of skeletal muscle", "D": "Muscular dystrophy - An auto immune disorder causing progressive degeneration of skeletal muscle"}, "correctAnswer": "A"},
  {"questionNumber": 24, "questionText": "Which of the following is present between the adjacent bones of the vertebral column?", "questionImageURL": "", "options": {"A": "Intercalated discs", "B": "Cartilage", "C": "Areolar tissue", "D": "Smooth muscle"}, "correctAnswer": "B"},
  {"questionNumber": 25, "questionText": "Match List I with List II. List I (Type of Joint) List II (Found between) A. Cartilaginous Joint i. Between flat skull bones B. Ball and Socket Joint ii. Between adjacent vertebrae in vertebral column C. Fibrous Joint iii. Between carpal and metacarpal of thumb D. Saddle Joint iv. Between Humerus and Pectoral girdle", "questionImageURL": "", "options": {"A": "A-ii, B-iv, C-i, D-iii", "B": "A-i, B-iv, C-iii, D-ii", "C": "A-ii, B-iv, C-iii, D-i", "D": "A-iii, B-i, C-ii, D-iv"}, "correctAnswer": "A"},
  {"questionNumber": 26, "questionText": "Which of the following statements are correct regarding skeletal muscle? A. Muscle bundles are held together by collagenous connective tissue layer called fascicle. B. Sarcoplasmic reticulum of muscle fibre is a store house of calcium ions. C. Striated appearance of skeletal muscle fibre is due to distribution pattern of actin and myosin proteins. D. M line is considered as functional unit of contraction called sarcomere.", "questionImageURL": "", "options": {"A": "B and C only", "B": "A, C and D only", "C": "C and D only", "D": "A, B and C only"}, "correctAnswer": "A"},
  {"questionNumber": 27, "questionText": "Which of the following are Autoimmune disorders? A. Myasthenia gravis B. Rheumatoid arthritis C. Gout D. Muscular dystrophy E. Systemic Lupus Erythematosus (SLE)", "questionImageURL": "", "options": {"A": "A, B & D only", "B": "A, B and E, only", "C": "B, C and E, only", "D": "C, D and E, only"}, "correctAnswer": "B"},
  {"questionNumber": 28, "questionText": "Three types of muscles are given as a, b and c. identify the correct matching pair along with their location in human body.", "questionImageURL": "https://firebasestorage.googleapis.com/v0/b/neet-trackr.appspot.com/o/flashback_q28.png?alt=media", "options": {"A": "(a) Smooth - Toes, (b) Skeletal - Legs, (c) Cardiac - Heart", "B": "(a) Skeletal - Triceps, (b) Smooth - Stomach, (c) Cardiac - Heart", "C": "(a) Skeletal - Biceps, (b) Involuntary - Intestine, (c) Smooth - Heart", "D": "(a) Involuntary - Nose tip, (b) Skeletal - Bone, (c) Cardiac - Heart"}, "correctAnswer": "B"},
  {"questionNumber": 29, "questionText": "Match List I and List II: List I: A. Fibrous joints, B. Cartilaginous joints, C. Hinge joints, D. Ball and socket joints; List II: I. Adjacent vertebrae, limited movement, II. Humerus and Pectoral girdle, rotational movement, III. Skull, don't allow any movement, IV. Knee, help in locomotion", "questionImageURL": "", "options": {"A": "A-IV, B-II, C-III, D-I", "B": "A-I, B-III, C-II, D-IV", "C": "A-II, B-III, C-I, D-IV", "D": "A-III, B-I, C-IV, D-II"}, "correctAnswer": "D"},
  {"questionNumber": 30, "questionText": "Match List-I with List-II: List-I (Location of joint): A. Joint between humerus and pectoral girdle, B. Knee joint, C. Joint between atlas and axis, D. Joint between carpals; List-II (Type of Joint): I. Gliding joint, II. Ball and Socket joint, III. Hinge joint, IV. Pivot joint", "questionImageURL": "", "options": {"A": "A-II, B-III, C-IV, D-I", "B": "A-III, B-II, C-I, D-IV", "C": "A-I, B-IV, C-III, D-II", "D": "A-II, B-I, C-III, D-IV"}, "correctAnswer": "A"},
  {"questionNumber": 31, "questionText": "Select the correct statements regarding mechanism of muscle contraction. A. It is initiated by a signal sent by CNS via sensory neuron. B. Neurotransmitter generates action potential in the sarcolemma. C. Increases Ca⁺⁺ level leads to the binding of calcium with troponin on actin filaments. D. Masking of active site for actin is activated. E. Utilising the energy from ATP hydrolysis to form cross bridge.", "questionImageURL": "", "options": {"A": "B, C and E only", "B": "C, D and E only", "C": "A and D only", "D": "B, D and E only"}, "correctAnswer": "A"},
  {"questionNumber": 32, "questionText": "Match List - I with List II. List-I: A. Emphysema, B. Angina Pectoris, C. Glomerulo-Nephritis, D. Tetany; List-II: I. Rapid spasms in muscle due to low Ca⁺⁺ in body fluid, II. Damaged alveolar walls and decreased respiratory surface, III. Acute chest pain when not enough oxygen is reaching to heart muscle, IV. Inflammation of glomeruli of kidney", "questionImageURL": "", "options": {"A": "A-II, B-III, C-IV, D-I", "B": "A-III, B-I, C-IV, D-II", "C": "A-III, B-I, C-II, D-IV", "D": "A-II, B-IV, C-III, D-I"}, "correctAnswer": "A"}
];
export default questions;

    